### ISSUE TITLE
Bind logging based on platform

### ISSUE THREAD

**Issue by esuomi** [siilisolutions/hedge#12]
Logging currently works but is in no way clean or even managed; what it binds to is accidental and while it thankfully works as expected, it is not exactly how it should work as _intended_.

**Comment by esuomi** [comment]
It was recently decided on Gitter that we should use [Timbre](https://github.com/ptaoussanis/timbre) for this and implement platform specific logging using its middleware appenders.

**Comment by jikuja** [comment]
Implemented in dev
