### ISSUE TITLE
A task to build the artifacts, without need to deploy

### ISSUE THREAD

**Issue by erkkikeranen** [siilisolutions/hedge#13]
Currently in the upcoming 0.0.2 it looks like you can't just build the artifacts, would it be possible to have a build task so that you can just build the artifacts?

**Comment by jikuja** [comment]
Fixed in unreleased v0.0.2

**Comment by jikuja** [comment]
Done in aws-deploy branch for AWS and for Azure in commit 735979836d6f6c305b08d34521bd2f2d2e446c6c and 94c721c1fcb831ff6d5d4a2f7673a8c2fc48bc19

New release coming soon. Closing now.
