### ISSUE TITLE
Update authentication to use SDK 2.0 features

### ISSUE THREAD

**Issue by erkkikeranen** [siilisolutions/hedge#37]
Currently Hedge seems to depend on the authentication.properties file which must be manually generated.

The Java SDK could use directly the JSON format that azure CLI can output with the command 

`az ad sp create-for-rbac --name "nameOfApplication" --sdk-auth`

This would also be compatible with the other sdk authentication files and would support certificate authentication.

Also it looks like there is no actual documentation available, how you really get started, authenticate with Azure etc.

https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md

**Comment by jikuja** [comment]
Already supported. Azure Java SDK got support for JSON credential files in v1.2.0. Hedge is using v1.2.1.

Both password based and certificate based format works fine,
