### ISSUE TITLE
Feature request: Passing credentials as command line parameters or ENV variables instead of authentication file when deploying to Azure

### ISSUE THREAD

**Issue by erkkikeranen** [siilisolutions/hedge#39]
In some cases it would be nice if a CI / CD runner could deploy without having the Azure Service Principal file lying on the filesystem. 

Ideal would be that there would be different authentications available to cover all use cases:
* properties file
* file output by `az cli --sdk-auth output`
* command line parameters

So that you could pass the credentials of the service principal as env variables in runner environment from command line, or if Hedge would use own set of ENV variables to look for.

Usage example idea:
`boot hedge-azure -r myresgrp -a myfuncapp --username $USERNAME --password $PASSWORD --tenant $TENANT`

Or:

`boot hedge-azure -r myresgrp -a myfuncapp`
given env variables HEDGE_AZURE_USERNAME, HEDGE_AZURE_PASSWORD, HEDGE_AZURE_TENANT etc is defined

Why:
* Solves some hassle of generating/storing/cleaning up service principal file in the CI pipeline
* Gives some options on how to authenticate with Azure in different usecases

**Comment by jikuja** [comment]
Fixed for Azure
